name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: | 
          make init

      - name: Run tests
        run: | 
          make test

      - name: build Docker image
        run: | 
          make build
